# Data Loading and Understanding

In [21]:
import pandas as pd

#Load and read dataset

rpw_path="../data/rpw_dataset_2011_2025_q3.xlsx"
df= pd.read_excel(rpw_path, sheet_name="Dataset (from Q2 2016)")

#Qick Checks
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())


print("\nFirst 5 rows:")
display(df.head())

print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False).head(20).to_string())

Shape: (204469, 47)

Columns:
['id', 'period', 'source_code', 'source_name', 'source_region', 'source_income', 'source_lending', 'source_G8G20', 'destination_code', 'destination_name', 'destination_region', 'destination_income', 'destination_lending', 'destination_G8G20', 'firm', 'firm_type', 'payment instrument', 'access point', 'speed actual', 'cc1 lcu amount', 'cc1 denomination amount', 'cc1 lcu code', 'cc1 lcu fee', 'cc1 lcu fx rate', 'cc1 fx margin', 'cc1 total cost %', 'cc2 lcu amount', 'cc2 denomination amount', 'cc2 lcu code', 'cc2 lcu fee', 'cc2 lcu fx rate', 'cc2 fx margin', 'cc2 total cost %', 'inter lcu bank fx', 'transparent', 'Standard Note', 'note2', 'receiving network coverage', 'pickup location', 'pickup method', 'date', 'corridor', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46']

First 5 rows:

,id,period,source_code,source_name,source_region,source_income,source_lending,source_G8G20,destination_code,destination_name,...,receiving network coverage,pickup location,pickup method,date,corridor,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,620160001,2016_2Q,AGO,Angola,Sub-Saharan Africa,Lower middle income,IBRD,..,NAM,Namibia,...,High,Agent,Cash,11/May/2016,AGONAM,NaN,NaN,NaN,NaN,NaN
1,620160002,2016_2Q,AGO,Angola,Sub-Saharan Africa,Lower middle income,IBRD,..,NAM,Namibia,...,High,Agent,Cash,11/May/2016,AGONAM,NaN,NaN,NaN,NaN,NaN
2,620160003,2016_2Q,AGO,Angola,Sub-Saharan Africa,Lower middle income,IBRD,..,NAM,Namibia,...,Low,NaN,Bank account,11/May/2016,AGONAM,NaN,NaN,NaN,NaN,NaN
3,620160004,2016_2Q,ARE,United Arab Emirates,..,High income,..,..,BGD,Bangladesh,...,High,Agent,Cash,09/May/2016,AREBGD,NaN,NaN,NaN,NaN,NaN
4,620160005,2016_2Q,ARE,United Arab Emirates,..,High income,..,..,BGD,Bangladesh,...,High,Agent,Cash,09/May/2016,AREBGD,NaN,NaN,NaN,NaN,NaN

Missing values:
note2                  204181
Unnamed: 43            197999
Unnamed: 42            197999
Unnamed: 45            197999
Unnamed: 44            197999
Unnamed: 46            197999
Standard Note          155892
pickup location        115614
cc2 total cost %         1038
cc2 lcu fee              1038
cc2 lcu fx rate          1038
cc2 fx margin            1037
cc1 lcu fee                21
cc1 lcu fx rate            21
cc1 fx margin              17
cc1 total cost %           17
firm                        0
destination_lending         0
destination_G8G20           0
destination_region          0

In [22]:
# Check key columns 
key_cols = [
    "period",
    "source_name",
    "destination_name",
    "firm_type",
    "payment instrument",
    "access point",
    "cc1 total cost %",
    "corridor"
]

display(df[key_cols].head(10))

,period,source_name,destination_name,firm_type,payment instrument,access point,cc1 total cost %,corridor
0,2016_2Q,Angola,Namibia,Money Transfer Operator,Cash,Agent,16.28,AGONAM
1,2016_2Q,Angola,Namibia,Money Transfer Operator,"Bank account transfer,Cash",Agent,14.19,AGONAM
2,2016_2Q,Angola,Namibia,Bank,Bank account transfer,Bank branch,27.50,AGONAM
3,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.13,AREBGD
4,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.17,AREBGD
5,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,0.62,AREBGD
6,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.13,AREBGD
7,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.13,AREBGD
8,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.22,AREBGD
9,2016_2Q,United Arab Emirates,Bangladesh,Money Transfer Operator,Cash,Agent,2.17,AREBGD

## Europe-Africa Coverage

In [23]:
# Quick look at source and destination countries
print("Unique source countries:", df["source_name"].nunique())
print("Unique destination countries:", df["destination_name"].nunique())

print("\nTop source countries:")
print(df["source_name"].value_counts().head(15).to_string())

print("\nTop destination countries:")
print(df["destination_name"].value_counts().head(15).to_string())

Unique source countries: 51
Unique destination countries: 108

Top source countries:
source_name
United States           29542
United Kingdom          23857
Italy                   15334
Germany                 13419
Australia               11626
France                   9266
Canada                   8691
New Zealand              7833
Singapore                7184
Spain                    7046
South Africa             6833
Malaysia                 5809
Japan                    5215
United Arab Emirates     5011
Netherlands              4636

Top destination countries:
destination_name
India          15757
Philippines    14613
Vietnam         8936
China           8604
Bangladesh      6762
Pakistan        6556
Sri Lanka       6196
Indonesia       5912
Morocco         5650
Nigeria         5306
Brazil          4357
Ghana           4356
Kenya           4108
Thailand        4078
Nepal           4020

In [24]:
# Understand the time periods
print("Unique periods (first 10):")
print(df["period"].unique()[:10])
print(f"\nTotal unique periods: {df['period'].nunique()}")

# Understand firm types (channels)
print("\nFirm types and their counts:")
print(df["firm_type"].value_counts().to_string())

# Quick stats on the cost variable
print("\nCost % statistics:")
print(df["cc1 total cost %"].describe().to_string())

Unique periods (first 10):
<StringArray>
['2016_2Q', '2016_3Q', '2016_4Q', '2017_1Q', '2017_2Q', '2017_3Q', '2017_4Q',
 '2018_1Q', '2018_2Q', '2018_3Q']
Length: 10, dtype: str

Total unique periods: 37

Firm types and their counts:
firm_type
Money Transfer Operator                       165547
Bank                                           32475
Money Transfer Operator / Post office           1893
Post office                                     1698
Bank / Money Transfer Operator                  1383
Mobile Operator                                 1037
Non-Bank FI                                      182
Money Transfer Operator / Post Office            103
Bank/Post office                                  88
Money Transfer Operator / Building Society        38
Post Office                                       25

Cost % statistics:
count    204452.000000
mean          6.573387
std           6.215563
min         -58.920000
25%           3.100000
50%           5.040000
75%           8.140000
max         307.200000

In [25]:
# How are digital vs traditional channels distinguished in this data?
print("Unique payment instruments:")
print(df["payment instrument"].value_counts().head(20).to_string())

print("\nUnique access points:")
print(df["access point"].value_counts().head(20).to_string())

Unique payment instruments:
payment instrument
Cash                                            65699
Bank account transfer                           58764
Debit card                                      23922
Credit Card                                     16421
Debit/credit card                               10566
Bank account transfer,Debit/credit card         10288
Credit Card,Debit card                           4005
Cash,Debit/credit card                           3841
Bank account transfer,Cash                       3030
Credit card                                      2664
Bank account transfer,Credit Card,Debit card     2190
Mobile money                                     1601
Bank account transfer,Debit card                  535
Prepaid card                                      308
Cash,Credit Card,Debit card                       201
Cash,Debit card                                   190
Bank account transfer,Cash,Mobile money            96
Bank account transfer,Credit Card                  71
Cash,Mobile money                                  38
Cash,Credit Card                                   22

Unique access points:
access point
Internet                            99969
Agent                               69702
Bank branch                         13385
Bank branch,Call Center              6183
Call Center                          3020
Agent,Internet                       2628
Agent,Call Center                    2108
Post Office branch                   1752
Mobile phone                         1623
Bank branch,Call Center,Internet     1540
Bank branch,Internet                 1208
Agent,Call Center,Internet            685
Internet,Post Office branch           319
Call Center,Internet                  134
ATM Network                            89
Agent,Internet,Mobile phone            56
Post Office                            45
Internet,Post Office                   12
ATM Network,Internet                    8
Call Center,Post Office                 1

## Data Cleaning

In [26]:
# Keep only the columns we are likely to use first
cols_to_keep = [
    "period",
    "source_name",
    "source_region",
    "destination_name",
    "destination_region",
    "firm_type",
    "payment instrument",
    "access point",
    "cc1 total cost %",
    "corridor"
]

df_work = df[cols_to_keep].copy()

# Rename the cost column
df_work = df_work.rename(columns={"cc1 total cost %": "remittance_cost_pct"})

print("Working dataframe shape:", df_work.shape)
display(df_work.head())

Working dataframe shape: (204469, 10)

,period,source_name,source_region,destination_name,destination_region,firm_type,payment instrument,access point,remittance_cost_pct,corridor
0,2016_2Q,Angola,Sub-Saharan Africa,Namibia,Sub-Saharan Africa,Money Transfer Operator,Cash,Agent,16.28,AGONAM
1,2016_2Q,Angola,Sub-Saharan Africa,Namibia,Sub-Saharan Africa,Money Transfer Operator,"Bank account transfer,Cash",Agent,14.19,AGONAM
2,2016_2Q,Angola,Sub-Saharan Africa,Namibia,Sub-Saharan Africa,Bank,Bank account transfer,Bank branch,27.50,AGONAM
3,2016_2Q,United Arab Emirates,..,Bangladesh,South Asia,Money Transfer Operator,Cash,Agent,2.13,AREBGD
4,2016_2Q,United Arab Emirates,..,Bangladesh,South Asia,Money Transfer Operator,Cash,Agent,2.17,AREBGD

In [27]:
# check for Missing values in the working dataframe
print(df_work.isnull().sum())

#summary of the cost column
print("\nCost summary:")
print(df_work["remittance_cost_pct"].describe())

period                  0
source_name             0
source_region           0
destination_name        0
destination_region      0
firm_type               0
payment instrument      0
access point            0
remittance_cost_pct    17
corridor                0
dtype: int64

Cost summary:
count    204452.000000
mean          6.573387
std           6.215563
min         -58.920000
25%           3.100000
50%           5.040000
75%           8.140000
max         307.200000
Name: remittance_cost_pct, dtype: float64

In [28]:
# Filter to selected European sender countries
european_senders = [
    "United Kingdom", "Italy", "Germany", "France", "Spain",
    "Netherlands", "Belgium", "Portugal", "Sweden", "Austria"
]

df_europe = df_work[df_work["source_name"].isin(european_senders)].copy()

print("Rows after filtering to selected European senders:", len(df_europe))
print("\nEuropean senders in filtered data:")
print(df_europe["source_name"].value_counts())

Rows after filtering to selected European senders: 82057

European senders in filtered data:
source_name
United Kingdom    23857
Italy             15334
Germany           13419
France             9266
Spain              7046
Netherlands        4636
Austria            3132
Belgium            2401
Sweden             1851
Portugal           1115
Name: count, dtype: int64

In [29]:
# Filter to African destination regions
african_regions = ["Sub-Saharan Africa", "Middle East & North Africa"]

df_eu_africa = df_europe[df_europe["destination_region"].isin(african_regions)].copy()

print("Rows after filtering to Africa-bound corridors:", len(df_eu_africa))
print("\nTop destination countries:")
print(df_eu_africa["destination_name"].value_counts().head(20))

Rows after filtering to Africa-bound corridors: 30971

Top destination countries:
destination_name
Morocco             5331
Nigeria             3421
Ghana               2799
Senegal             1590
Tunisia             1310
Lebanon             1259
Ethiopia            1084
Togo                1054
Kenya                972
Somalia              917
Uganda               837
Côte d'Ivoire        768
Egypt, Arab Rep.     764
Tanzania             705
Gambia, The          674
Cameroon             672
Rwanda               661
South Africa         659
Sierra Leone         603
Zimbabwe             583
Name: count, dtype: int64

### Clean Cost Values

In [30]:
# Check suspicious cost values before filtering
print("Rows with negative cost values:", (df_eu_africa["remittance_cost_pct"] < 0).sum())
print("Rows with cost above 30%:", (df_eu_africa["remittance_cost_pct"] > 30).sum())

print("\nCost summary before filtering:")
print(df_eu_africa["remittance_cost_pct"].describe())

Rows with negative cost values: 297
Rows with cost above 30%: 91

Cost summary before filtering:
count    30971.000000
mean         6.516177
std          4.654660
min        -58.920000
25%          3.610000
50%          5.510000
75%          8.400000
max         53.770000
Name: remittance_cost_pct, dtype: float64

In [31]:
# Remove rows with missing or unrealistic remittance cost values
df_eu_africa = df_eu_africa[
    (df_eu_africa["remittance_cost_pct"].notna()) &
    (df_eu_africa["remittance_cost_pct"] >= 0) &
    (df_eu_africa["remittance_cost_pct"] <= 30)
].copy()

print("Rows after removing missing and unrealistic cost values:", len(df_eu_africa))
print("\nCost summary after filtering:")
print(df_eu_africa["remittance_cost_pct"].describe())

Rows after removing missing and unrealistic cost values: 30583

Cost summary after filtering:
count    30583.000000
mean         6.528104
std          4.195954
min          0.000000
25%          3.660000
50%          5.550000
75%          8.400000
max         29.910000
Name: remittance_cost_pct, dtype: float64

In [32]:
print("Firm types in cleaned Europe-Africa data:")
print(df_eu_africa["firm_type"].value_counts().to_string())

print("\nTop payment instruments in cleaned Europe-Africa data:")
print(df_eu_africa["payment instrument"].value_counts().head(20).to_string())

print("\nTop access points in cleaned Europe-Africa data:")
print(df_eu_africa["access point"].value_counts().head(20).to_string())

Firm types in cleaned Europe-Africa data:
firm_type
Money Transfer Operator                  26860
Bank                                      1717
Money Transfer Operator / Post office      940
Bank / Money Transfer Operator             479
Post office                                421
Mobile Operator                             75
Bank/Post office                            58
Money Transfer Operator / Post Office       28
Post Office                                  5

Top payment instruments in cleaned Europe-Africa data:
payment instrument
Cash                                            7368
Bank account transfer                           5790
Debit card                                      5186
Credit Card                                     4056
Bank account transfer,Debit/credit card         2457
Debit/credit card                               1570
Cash,Debit/credit card                          1266
Credit Card,Debit card                          1057
Bank account transfer,Credit Card,Debit card     604
Credit card                                      548
Bank account transfer,Cash                       217
Prepaid card                                     171
Bank account transfer,Debit card                  80
Mobile money                                      78
Cash,Debit card                                   57
Cash,Credit Card,Debit card                       47
Bank account transfer,Credit Card                 17
Cash,Credit Card                                  10
Bank account transfer,Cash,Mobile money            2
Bank account transfer,Cash,Debit card              2

Top access points in cleaned Europe-Africa data:
access point
Internet                            17877
Agent                                9029
Bank branch                          1101
Post Office branch                    613
Bank branch,Call Center               512
Call Center                           372
Agent,Call Center                     324
Internet,Post Office branch           244
Agent,Internet                        145
Bank branch,Internet                  143
Mobile phone                           75
Bank branch,Call Center,Internet       69
Agent,Call Center,Internet             32
Call Center,Internet                   21
Post Office                            16
Internet,Post Office                    9
Call Center,Internet,Post Office        1

### Channel Classification

In [33]:
# Create a first digital vs traditional channel flag using access point
digital_access_points = ["Internet", "Mobile phone"]
traditional_access_points = ["Agent", "Bank branch", "Post Office branch", "Post Office", "Call Center"]

def classify_channel(access_point):
    if pd.isna(access_point):
        return "Unclear"
    if any(item in access_point for item in digital_access_points):
        return "Digital"
    if any(item in access_point for item in traditional_access_points):
        return "Traditional"
    return "Unclear"

df_eu_africa["channel_group"] = df_eu_africa["access point"].apply(classify_channel)

print(df_eu_africa["channel_group"].value_counts())

channel_group
Digital        18616
Traditional    11967
Name: count, dtype: int64

In [34]:
# Compare average remittance cost by channel group
print(df_eu_africa.groupby("channel_group")["remittance_cost_pct"].describe().round(2))

                 count  mean   std  min   25%   50%    75%    max
channel_group
Digital        18616.0  5.33  3.50  0.0  2.94  4.52   6.85  29.80
Traditional    11967.0  8.39  4.51  0.0  5.23  7.34  10.38  29.91

# Corridor-level comparison and ranking

### How does the pattern vary by corridor, destination, and time?

In [35]:
#check whether this pattern holds across corridors, not just overall
# Compare average cost by corridor and channel group
corridor_channel_summary = (
    df_eu_africa.groupby(["corridor", "source_name", "destination_name", "channel_group"])["remittance_cost_pct"]
    .mean()
    .reset_index()
)

print(corridor_channel_summary.head(10))
print("\nNumber of unique corridors:", corridor_channel_summary["corridor"].nunique())

  corridor source_name  destination_name channel_group  remittance_cost_pct
0   BELCOD     Belgium  Congo, Dem. Rep.       Digital             6.381973
1   BELCOD     Belgium  Congo, Dem. Rep.   Traditional             8.502553
2   BELDZA     Belgium           Algeria       Digital             8.531667
3   BELDZA     Belgium           Algeria   Traditional             9.478500
4   BELMAR     Belgium           Morocco       Digital             4.150115
5   BELMAR     Belgium           Morocco   Traditional             5.524646
6   DEUGHA     Germany             Ghana       Digital             6.494460
7   DEUGHA     Germany             Ghana   Traditional            12.663519
8   DEULBN     Germany           Lebanon       Digital             9.125556
9   DEULBN     Germany           Lebanon   Traditional            12.691617

Number of unique corridors: 51

In [36]:
# Pivot to compare digital vs traditional side by side
corridor_compare = corridor_channel_summary.pivot_table(
    index=["corridor", "source_name", "destination_name"],
    columns="channel_group",
    values="remittance_cost_pct"
).reset_index()

print(corridor_compare.head(10))
print("\nMissing values by column:")
print(corridor_compare.isnull().sum())

channel_group corridor source_name  destination_name   Digital  Traditional
0               BELCOD     Belgium  Congo, Dem. Rep.  6.381973     8.502553
1               BELDZA     Belgium           Algeria  8.531667     9.478500
2               BELMAR     Belgium           Morocco  4.150115     5.524646
3               DEUGHA     Germany             Ghana  6.494460    12.663519
4               DEULBN     Germany           Lebanon  9.125556    12.691617
5               DEUMAR     Germany           Morocco  5.044217     8.132959
6               DEUNGA     Germany           Nigeria  3.760629     9.575875
7               DEUTGO     Germany              Togo  3.785273     7.520309
8               ESPMAR       Spain           Morocco  4.117933     6.093191
9               ESPNGA       Spain           Nigeria  3.954815     7.068287

Missing values by column:
channel_group
corridor            0
source_name         0
destination_name    0
Digital             0
Traditional         0
dtype: int64

In [37]:
# calculate the cost gap and rank the corridors

# Calculate the digital advantage / cost gap
corridor_compare["cost_gap"] = corridor_compare["Traditional"] - corridor_compare["Digital"]

# Sort corridors by the size of the gap
corridor_compare = corridor_compare.sort_values("cost_gap", ascending=False).reset_index(drop=True)

print(corridor_compare.head(15))

channel_group corridor     source_name destination_name   Digital  \
0               GBRLBN  United Kingdom          Lebanon  7.720661
1               GBRTZA  United Kingdom         Tanzania  5.244908
2               FRALBN          France          Lebanon  5.973977
3               DEUGHA         Germany            Ghana  6.494460
4               DEUNGA         Germany          Nigeria  3.760629
5               GBRETH  United Kingdom         Ethiopia  5.061910
6               GBRUGA  United Kingdom           Uganda  4.880803
7               GBRZAF  United Kingdom     South Africa  6.175700
8               SWELBN          Sweden          Lebanon  7.044899
9               GBRRWA  United Kingdom           Rwanda  7.227756
10              GBRZMB  United Kingdom           Zambia  6.551122
11              FRAMDG          France       Madagascar  6.463680
12              ITANGA           Italy          Nigeria  4.094977
13              ITASEN           Italy          Senegal  3.325583
14              SWESOM          Sweden          Somalia  6.775032

channel_group  Traditional  cost_gap
0                14.444912  6.724251
1                11.699006  6.454098
2                12.373960  6.399983
3                12.663519  6.169059
4                 9.575875  5.815246
5                10.807153  5.745243
6                10.163902  5.283100
7                11.050764  4.875064
8                11.721875  4.676976
9                11.697708  4.469952
10               11.015181  4.464059
11               10.756259  4.292579
12                8.342041  4.247063
13                7.343774  4.018191
14               10.756519  3.981486

In [38]:
# Quick summary of the gap
print(corridor_compare["cost_gap"].describe())

print("\nTop 10 corridors with the largest digital advantage:")
print(
    corridor_compare[["source_name", "destination_name", "Digital", "Traditional", "cost_gap"]]
    .head(10)
    .to_string(index=False)
)

count    51.000000
mean      3.280398
std       1.573094
min       0.723295
25%       2.057774
50%       3.113472
75%       4.132627
max       6.724251
Name: cost_gap, dtype: float64

Top 10 corridors with the largest digital advantage:
   source_name destination_name  Digital  Traditional  cost_gap
United Kingdom          Lebanon 7.720661    14.444912  6.724251
United Kingdom         Tanzania 5.244908    11.699006  6.454098
        France          Lebanon 5.973977    12.373960  6.399983
       Germany            Ghana 6.494460    12.663519  6.169059
       Germany          Nigeria 3.760629     9.575875  5.815246
United Kingdom         Ethiopia 5.061910    10.807153  5.745243
United Kingdom           Uganda 4.880803    10.163902  5.283100
United Kingdom     South Africa 6.175700    11.050764  4.875064
        Sweden          Lebanon 7.044899    11.721875  4.676976
United Kingdom           Rwanda 7.227756    11.697708  4.469952

### Identify top corridors

In [40]:
# Select top 12 corridors by digital advantage

top_corridors = corridor_compare.head(12)["corridor"].tolist()

print("Top 12 corridors selected for small multiples:")
print(top_corridors)

Top 12 corridors selected for small multiples:
['GBRLBN', 'GBRTZA', 'FRALBN', 'DEUGHA', 'DEUNGA', 'GBRETH', 'GBRUGA', 'GBRZAF', 'SWELBN', 'GBRRWA', 'GBRZMB', 'FRAMDG']

In [41]:
# Filter cleaned data to only those top 12 corridors
df_top_corridors = df_eu_africa[df_eu_africa["corridor"].isin(top_corridors)].copy()

print("Rows in top-corridor dataset:", len(df_top_corridors))
print("\nCorridors included:")
print(df_top_corridors["corridor"].value_counts())

Rows in top-corridor dataset: 6881

Corridors included:
corridor
DEUGHA    918
GBRUGA    828
DEUNGA    765
GBRTZA    670
GBRZAF    657
GBRRWA    651
GBRZMB    567
GBRETH    500
FRAMDG    397
GBRLBN    341
SWELBN    310
FRALBN    277
Name: count, dtype: int64

In [42]:
# Check the time coverage of the selected top corridors
time_check = (
    df_top_corridors.groupby("corridor")["period"]
    .nunique()
    .sort_values(ascending=False)
)

print("Number of unique periods per selected corridor:")
print(time_check)

Number of unique periods per selected corridor:
corridor
DEUGHA    37
DEUNGA    37
FRAMDG    37
GBRETH    37
GBRZMB    37
GBRRWA    37
GBRTZA    37
GBRUGA    37
GBRZAF    37
FRALBN    36
GBRLBN    36
SWELBN    36
Name: period, dtype: int64